### ISSUE TITLE
Add support to vCenter/vSphere 6.7

### ISSUE THREAD

**Issue by ccesario** [apache/cloudstack#2700]
##### ISSUE TYPE

 * Feature Idea

##### COMPONENT NAME

~~~
Apache CloudStack Core, Hypervisor
~~~

##### CLOUDSTACK VERSION

~~~
Apache CloudStack 4.11.1.0
~~~

##### CONFIGURATION

~~~
N/A
~~~

##### OS / ENVIRONMENT

~~~
Apache CloudStack 4.11.1.0 and vCenter 6.7
~~~

##### SUMMARY

~~~
Currently the last stable VMware version is 6.7 and Cloudstack code support until VMware 6.5.
It would interesting add support to this new version - 6.7
~~~

##### STEPS TO REPRODUCE

~~~
N/A
~~~

##### EXPECTED RESULTS

~~~
N/A
~~~

##### ACTUAL RESULTS

~~~
N/A
~~~

**Comment by resmo** [comment]
This has been addressed in #2727 

closing?

**Comment by rhtyd** [comment]
@resmo we've only bumped and added support for the v6.7 sdk but we could n't get it (smoke) tested against vsphere vcenter 6.7 version.

**Comment by rhtyd** [comment]
@resmo can you test latest 4.11 branch and confirm if it works with Vmware 6.7?

**Comment by resmo** [comment]
@rhtyd we only have vsphere 6.5 in test

**Comment by onitake** [comment]
We still won't be able to test this against 6.7, but if doesn't break 5.5 and 6.5 compatibility, I think it's ok to ship it.

We're planning to bump our test environment to 6.7 in August and will be able to test then.
