### ISSUE TITLE
issues with live migration on centos (was: Trillian test failures)

### ISSUE THREAD

**Issue by weizhouapache** [apache/cloudstack#4757]
@DaanHoogland @rhtyd 
this needs research.

Test | Result | Time (s) | Test File
-- | -- | -- | --
test_01_migrate_VM_and_root_volume | Error | 63.19 | test_vm_life_cycle.py
test_02_migrate_VM_with_two_data_disks | Error | 48.09 | test_vm_life_cycle.py

https://github.com/apache/cloudstack/pull/4736#issuecomment-789312916

management logs
```
2021-03-02 18:50:44,203 DEBUG [o.a.c.s.v.VolumeServiceImpl] (Work-Job-Executor-106:ctx-a6be1c7c job-2200/job-2201 ctx-10684199) (logid:f366d768) Failed to copy volume
com.cloud.utils.exception.CloudRuntimeException: Copy operation failed in 'StorageSystemDataMotionStrategy.copyAsync': Exception during migrate: org.libvirt.LibvirtException: internal error: unable to execute QEMU command 'migrate': this feature or command is not currently supported
	at org.apache.cloudstack.storage.motion.StorageSystemDataMotionStrategy.copyAsync(StorageSystemDataMotionStrategy.java:1901)
	at org.apache.cloudstack.storage.motion.DataMotionServiceImpl.copyAsync(DataMotionServiceImpl.java:119)
	at org.apache.cloudstack.storage.volume.VolumeServiceImpl.migrateVolumes(VolumeServiceImpl.java:1645)
	at org.apache.cloudstack.engine.orchestration.VolumeOrchestrator.migrateVolumes(VolumeOrchestrator.java:1181)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrateWithStorage(VirtualMachineManagerImpl.java:3000)
	at com.cloud.vm.VirtualMachineManagerImpl.orchestrateMigrateWithStorage(VirtualMachineManagerImpl.java:5524)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloud.vm.VmWorkJobHandlerProxy.handleVmWorkJob(VmWorkJobHandlerProxy.java:107)
	at com.cloud.vm.VirtualMachineManagerImpl.handleVmWorkJob(VirtualMachineManagerImpl.java:5631)
	at com.cloud.vm.VmWorkJobDispatcher.runJob(VmWorkJobDispatcher.java:102)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.runInContext(AsyncJobManagerImpl.java:620)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable$1.run(ManagedContextRunnable.java:48)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext$1.call(DefaultManagedContext.java:55)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.callWithContext(DefaultManagedContext.java:102)
	at org.apache.cloudstack.managed.context.impl.DefaultManagedContext.runWithContext(DefaultManagedContext.java:52)
	at org.apache.cloudstack.managed.context.ManagedContextRunnable.run(ManagedContextRunnable.java:45)
	at org.apache.cloudstack.framework.jobs.impl.AsyncJobManagerImpl$5.run(AsyncJobManagerImpl.java:568)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-03-02 18:50:44,203 DEBUG [o.a.c.e.o.VolumeOrchestrator] (Work-Job-Executor-106:ctx-a6be1c7c job-2200/job-2201 ctx-10684199) (logid:f366d768) Failed to migrated vm VM[User|i-191-245-VM] along with its volumes. com.cloud.utils.exception.CloudRuntimeException: Copy operation failed in 'StorageSystemDataMotionStrategy.copyAsync': Exception during migrate: org.libvirt.LibvirtException: internal error: unable to execute QEMU command 'migrate': this feature or command is not currently supported
```

##### ISSUE TYPE

 * Bug Report
 * Improvement Request
 * Enhancement Request
 * Feature Idea
 * Documentation Report
 * Other

##### COMPONENT NAME

~~~

~~~

##### CLOUDSTACK VERSION

~~~

~~~

##### STEPS TO REPRODUCE

~~~

~~~

##### EXPECTED RESULTS

~~~

~~~

##### ACTUAL RESULTS

~~~

~~~

**Comment by DaanHoogland** [comment]
@weizhouapache the centos7 templates for kvm do not support life migration on ubuntu it should work fine. in #4727 I added an explicit test for host os in the test. this one is 13000 lines so not a pleasure to walkthrough, so
[`874a142` (#4727)](https://github.com/apache/cloudstack/pull/4727/commits/874a142f5047155c0eb194e2e501eb88a981095b) should do it in future trillian runs.
Also I'm looking into adding the test data on ubuntu but it gets drowned a bit.

**Comment by DaanHoogland** [comment]
So the real issue is life migration on centos, @weizhouapache , not the tests.

**Comment by weizhouapache** [comment]
> So the real issue is life migration on centos, @weizhouapache , not the tests.

@DaanHoogland yeah, I think so.

**Comment by rhtyd** [comment]
I think it's because of stock CentO7 libvirtd that does not support it, I think with qemu-kvm-ev this may work (like Ubuntu) [1]

[1] https://wiki.centos.org/SpecialInterestGroup/Virtualization

**Comment by DaanHoogland** [comment]
I'm not sure about the milestone, but I don't think this was introduced after 4.15

**Comment by weizhouapache** [comment]
> I'm not sure about the milestone, but I don't think this was introduced after 4.15

@DaanHoogland @rhtyd 
as Rohit said, this might not be caused by cloudstack changes, but by some recent changes in centos7 template/qemu/libvirt.
no idea if it is good idea to skip the testings.

**Comment by Pearl1594** [comment]
@rhtyd Live migration on centos8 seems to work fine. However, there is an issue noticed during live migration of VMs with data disks (test_02_migrate_VM_with_two_data_disks) that aren't created from snapshots (i.e., don't have a template id) - this has been addressed with - https://github.com/apache/cloudstack/pull/4771 cc @DaanHoogland @weizhouapache

**Comment by weizhouapache** [comment]
> @rhtyd Live migration on centos8 seems to work fine. However, there is an issue noticed during live migration of VMs with data disks (test_02_migrate_VM_with_two_data_disks) that aren't created from snapshots (i.e., don't have a template id) - this has been addressed with - #4698 cc @DaanHoogland @weizhouapache

#4698 has been merged into master/4.16, but  recent trillian test still fail

https://github.com/apache/cloudstack/pull/4577#issuecomment-796206333

**Comment by DaanHoogland** [comment]
I've added a PR to skip the tests on centos #4801, of course that does not solve the underlying problem but we can not implement features on hypervisors that do not support them.

**Comment by slavkap** [comment]
@DaanHoogland, is this[ #2983 ](https://github.com/apache/cloudstack/pull/2983) could help? In the PR, Nicolas explains the same problem on CentOS7. I have tested the migration of VM with volumes on my dev. with CentOS7 and qemu-kvm-ev-2.12.0-44.1.el7_8.1.x86_64 and it works

**Comment by DaanHoogland** [comment]
@slavkap is that qemu version stock or does the operator need to use external repos? and what libvirt version do you use for that.

**Comment by slavkap** [comment]
@DaanHoogland, it's sort of stock but does not come as default. In the PR's link above, Nicolas provides the steps to install it. I've followed these:
`yum install centos-release-qemu-ev`
`yum install qemu-kvm-ev`
libvirt version - 4.5.0

**Comment by rhtyd** [comment]
@andrijapanicsb @DaanHoogland @weizhouapache @wido @borisstoyanov @vladimirpetrov - should we be installing qemu-kvm-ev (enterprise version) than the default/stock version in our testing and advise the same in our docs? Looks like a lot of features are missing in the stock version and the ev releases are widely used by many CloudStack users

**Comment by andrijapanicsb** [comment]
"QEMU command 'migrate': this feature or command is not currently supported"

is the a long standing issue, where it worked in centos6, then feature revoked in centos7, even _yum install centos-release-qemu-ev; yum install qemu-kvm-ev_ - will NOT work, only when you use the qemu-kvm-ev from the oVirt repo - only that one comes with support for the live storage migration (and yes, Ubuntu works by default)

@weizhouapache @DaanHoogland  - as already discussed (with Daan), now that tests are running on python3, we are seeing those 2 tests fail and being reported as failed - while previously (while using python2) those tests were never reported to fail (but they certainly DID fail, as hypervisor centos7 doesn't support it) - I don't know why suddenly they are reported as failed, while they were NOT reported (but did fail if even attempted) previously.

So my idea is to skip this test - or at minimum to have the tests behave the same way they behaved while on python2 (skip it? or whatever way it worked before)

**Comment by DaanHoogland** [comment]
@andrijapanicsb the python3 version of the marvin tests are not merged yet, We are seeing these failures in python2.
I don't know what caused the failure to become visible but it is just that. They became visible without upgrading python.

**Comment by andrijapanicsb** [comment]
interesting - ok, my take on that would be to go to some older PR (few months back, when everything was fine) - download the marvin KVM tests results and observe those 2 tests and see if they were run at all, or failed, or whatever was happening...

**Comment by davidjumani** [comment]
After going Sherlock on this, discovered that the vm_lifecycle test was initially overridden by a custom one during the smoke tests, so the test_01_migrate_VM_and_root_volume && test_02_migrate_VM_with_two_data_disks tests were never run. After the overwrite was removed, the tests in the current repo were run and the problem surfaced
I'm for keeping the default packages and not installing any custom / ev versions and skipping these tests on Centos

**Comment by andrijapanicsb** [comment]
agree with that, revert to the "old" behaviour and let it go"

**Comment by rhtyd** [comment]
@andrijapanicsb we can ignore CentOS6, which has reached EOL, in the current release/context of CloudStack.

Given the limitations should we be promoting using Ubuntu now where things work out of the box (and say update the QIG guide?) and many CloudStack users notably Leaseweb, PCExtreme are already major users of Ubuntu/KVM with CloudStack? cc @wido @GabrielBrascher @weizhouapache 

I've started a thread on dev/user ML to discuss the use of qemu-kvm-ev with CloudStack (CentOS7, 8).

**Comment by wido** [comment]
> @andrijapanicsb we can ignore CentOS6, which has reached EOL, in the current release/context of CloudStack.
> 
> Given the limitations should we be promoting using Ubuntu now where things work out of the box (and say update the QIG guide?) and many CloudStack users notably Leaseweb, PCExtreme are already major users of Ubuntu/KVM with CloudStack? cc @wido @GabrielBrascher @weizhouapache
> 
> I've started a thread on dev/user ML to discuss the use of qemu-kvm-ev with CloudStack (CentOS7, 8).

I have no opinion about CentOS as we indeed use Ubuntu on all our servers.

**Comment by andrijapanicsb** [comment]
For the purpose of this issue, just ask @davidjumani to revert the change (done by whoever...) that made these test suddenly run, instead of being skipped, as they had been for lastbfew years.

**Comment by rhtyd** [comment]
@wido I think there are two things, (1) about how we run tests on PRs (the default test is CentOS7+kvm) and (2) if we should make our QIG (currently CentOS based) to also be Ubuntu based.
Closing this as the PR https://github.com/apache/cloudstack/pull/4801 fixes the issue by skipping tests that we know won't work, also per original commit 0fbf5006b87b6c5bc6188e3e1dd226a98c3bb453

**Comment by rhtyd** [comment]
I'll continue discussion on qemu-kvm-ev on dev/user ML and issue of QIG to be also based on Ubuntu.
