### ISSUE TITLE
Can't upload ISO - secondary storage not found

### ISSUE THREAD

**Issue by tetra12** [apache/cloudstack#5370]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
Storage, UI
~~~

##### CLOUDSTACK VERSION

~~~
4.16.0-Snapshot
~~~

##### CONFIGURATION

KVM
Advanced Zone
Local Storage
NO SSL/TLS

##### OS / ENVIRONMENT

Ubuntu 21.04

##### SUMMARY

Issue similar to #4734

Can't upload an ISO template - getting `Request Failed (530) There is no secondary storage VM for downloading template to image store adv-secondary-1`

Meanwhile, I do have a secondary storage:
```
(localcloud) 🐱 > list imagestores 
{
  "count": 1,
  "imagestore": [
    {
      "id": "bb112cc8-49ba-4b21-a558-ef4587b5ddec",
      "name": "adv-secondary-1",
      "protocol": "nfs",
      "providername": "NFS",
      "readonly": false,
      "scope": "ZONE",
      "url": "nfs://192.168.100.2/export/secondary",
      "zoneid": "a4c6793b-3f50-48ce-a2fb-665b96231c18",
      "zonename": "adv-zone-1"
    }
  ]
}
```
Secondary storage was mounted by hand inside SSVM and is currently accesimble from SSVM  as per [ssvm.log](https://github.com/apache/cloudstack/files/7046223/ssvm.log)

However, when I try to upload ISO from Local, I'm getting the following: `Request Failed (530) There's no secondary storage VM for downloading template to image stora adv-secondary-1`

I also tried to upload an ISO from a local web server ( on the same host, where ACS management and agent are running).
The ISO won't be uploaded despite the message "ISO was registered successfully" was displayed

##### STEPS TO REPRODUCE

~~~
1. Clone ACS master
2. Build deb packages for Ubuntu 21.04
3. Install ACS
4. Update the Global Cofiguration:
 - System.vm.use.local.storage -> true
 - Ca.plugin.root.auth.strictness -> false
5. Setup Advanced Zone without Security Groups
6. Launch Zone
7. Log into SSVM and run ssvm-check.sh
8. Mount a secondary storage by hand if needed ( I did in my case )
9. Run `cmk list imagestores` on a laptop and 
10. Go to Images -> Isos -> Upload ISO from Local
11. Specify the file
12. Click Add and get an error
~~~

##### EXPECTED RESULTS

~~~
Upload an ISO from Local
~~~

##### ACTUAL RESULTS

~~~
Upload ISO from Local fails with `Request Failed (530) There is no secondary storage VM for downloading template to image store`
~~~

**Comment by tetra12** [comment]
Hello @GabrielBrascher 
According to your advice, I made the following adjustments:

Host setup

cloudbr0 - 185.185.X.Y
cloudbr1 - 192.168.100.2

In the Physical Network Setup:

Public, Guest -> cloudbr0
Management, Storage -> cloudbr1

In the Global Settings:

management.network.cidr = 192.168.100.2/24 

Still no luck. The REAL problem is that I'm getting an exception inside the SSVM since it connects to the wrong host.

Inside the SSVM `/var/log/cloud.log` I'm getting:
```
2021-08-30 20:51:27,940 INFO  [utils.nio.NioClient] (main:null) Connecting to 185.185.X.Y:8250
2021-08-30 20:51:31,002 ERROR [utils.nio.NioConnection] (main:null) Unable to initialize the threads.
java.net.NoRouteToHostException: No route to host
        at java.base/sun.nio.ch.Net.connect0(Native Method)
```

And indeed `curl -vv telnet://185.185.X.Y` times out, BUT `curl -vv telnet://192.168.100.2` work.

I found that SSVM gets its IP from the `cmdline` file:
```
root@s-1-VM:~# cat /var/cache/cloud/cmd_line.json
{
"type": "cmdline",
"cmd_line": {
        "template": "domP",
        "type": "secstorage",
        "host": "185.185.X.Y",
        "port": "8250",
        "name": "s-1-VM",
        "zone": "1",
        "pod": "1",
        "guid": "s-1-VM",
        "workers": "5",
        "resource": "org.apache.cloudstack.storage.resource.NfsSecondaryStorageResource",
        "instance": "SecStorage",
        "sslcopy": "false",
        "role": "templateProcessor",
        "mtu": "1500",
        "eth2ip": "185.X.Y.116",
        "eth2mask": "255.255.255.192",
        "gateway": "185.X.Y.65",
        "public.network.device": "eth2",
        "eth0ip": "169.254.123.48",
        "eth0mask": "255.255.0.0",
        "eth1ip": "192.168.100.22",
        "eth1mask": "255.255.255.0",
        "mgmtcidr": "192.168.100.2/24",
        "localgw": "192.168.100.1",
        "private.network.device": "eth1",
        "internaldns1": "193.106.93.93",
        "internaldns2": "8.8.4.4",
        "dns1": "8.8.8.8",
        "dns2": "8.8.4.4",
        "nfsVersion": "null"
        }
}
```

@DaanHoogland 
SO indeed, `host = 185.185.X.Y`, which doesn't work for me. This address is taken from the `getControlp()` in `libvirt`, so that's the feature by design.

Any new ideas?

**Comment by tetra12** [comment]
Fixed after properly configuring SSVM

**Comment by unplugged216** [comment]
Since no actual resolve or method to achieve it was provide by OP, here is the documentation used to resolve the issue. 

https://cwiki.apache.org/confluence/display/CLOUDSTACK/SSVM%2C+templates%2C+Secondary+storage+troubleshooting

The ultimate issue is a bit more extensive. Following the above alone did not solve my problem. I need to modify the following files to reflect proper IPs before the agent made communication with the MS. 

`/var/cache/cloud/cmd_line.json`
`/var/cache/cloud/cmdline`

Then restart the service. Whole vm restart not required. 
`service cloud restart`
