### ISSUE TITLE
Problem WithCloudstack Installation Wizard 

### ISSUE THREAD

**Issue by ahmadamirahmadi007** [apache/cloudstack#6566]
##### ISSUE TYPE
 * Bug Report
##### COMPONENT NAME
UI
##### CLOUDSTACK VERSION
build 4.17 from main branch

##### CONFIGURATION
 N/A otherwise

##### OS / ENVIRONMENT
Ubuntu 20.04 LTS
Apache Maven 3.6.0
Java version: 11.0.15,
nodejs v16.16.0
Compute Nodes: Vmware Esxi

##### SUMMARY
i built cloudstack from source correctly with follow command. but in installation wizard in cloudstack UI, i encountered with an ERROR in Creating Cluster Step. i have put screenshot and details of logs here.

##### STEPS TO REPRODUCE
mvn clean install -P systemvm,developer
![cloudstack-ui](https://user-images.githubusercontent.com/104001728/180755849-ba85c6c7-46ba-4b21-8a83-5ff0bbb3f3a7.png)
![api-vm-com](https://user-images.githubusercontent.com/104001728/180755904-6e19043b-5296-42f9-9c2d-06202257c633.png)

meanwhile I Have and Error with this command for compile: 
mvn clean install -P systemvm,developer -Dnoredist
![compile-again](https://user-images.githubusercontent.com/104001728/180756483-4e2c1aca-9e82-4fc1-9be1-1865ce7a1c16.png)

##### EXPECTED RESULTS
Complete Wizard
##### ACTUAL RESULTS
I am stuck on the wizard

**Comment by nvazquez** [comment]
Hi @ahmadamirahmadi007 you can get the noredist dependencies from: https://github.com/shapeblue/cloudstack-nonoss and place them into your deps/ directory and installing them

**Comment by nvazquez** [comment]
After that, please consider this issue: https://github.com/apache/cloudstack/issues/6479 - it has been fixed and will be available from 4.17.1 onwards. For a zone creation can you consider an API client like cloudmonkey, for example: `create zone name=<NAME> dns1=<DNS1> internaldns1=<DNS2> networktype=Advanced localstorageenabled=true ... `?

**Comment by ahmadamirahmadi007** [comment]
i replaced all the files but unfortunately i have problem with the juniper plugin during the build. it is exactly previous error about juniper SRX. 
[INFO] Apache CloudStack Plugin - Juniper SRX ............. FAILURE [  9.812 s]
[INFO] Apache CloudStack VMware Base ...................... SKIPPED
[INFO] Apache CloudStack Plugin - Hypervisor VMware ....... SKIPPED
[INFO] Apache CloudStack Plugin - API VMware SIOC ......... SKIPPED
[INFO] Apache CloudStack Plugin - Veeam Backup and Recovery Plugin SKIPPED
[INFO] Apache CloudStack Plugin - Cisco VNMC .............. SKIPPED
[INFO] Apache CloudStack Plugin - MySQL HA Strategy ....... SKIPPED
[INFO] Apache CloudStack Framework - Spring Module ........ SKIPPED
[INFO] Apache CloudStack Secondary Storage Controller ..... SKIPPED
[INFO] Apache CloudStack Console Proxy .................... SKIPPED
[INFO] Apache CloudStack Console Proxy - RDP Client ....... SKIPPED
[INFO] Apache CloudStack Console Proxy - Server ........... SKIPPED
[INFO] Apache CloudStack System VM ........................ SKIPPED
[INFO] Apache CloudStack Client UI ........................ SKIPPED
[INFO] Apache CloudStack Framework - QuickCloud ........... SKIPPED
[INFO] Apache CloudStack Test ............................. SKIPPED
[INFO] Apache CloudStack Developer Mode ................... SKIPPED
[INFO] Apache CloudStack Developer Tools .................. SKIPPED
[INFO] Apache CloudStack apidocs .......................... SKIPPED
[INFO] Apache CloudStack marvin ........................... SKIPPED
[INFO] Apache CloudStack DevCloud4 ........................ SKIPPED
[INFO] Apache CloudStack DevCloud-KVM ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15:57 min
[INFO] Finished at: 2022-07-26T06:31:23Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project cloud-plugin-network-srx: Could not resolve dependencies for project org.apache.cloudstack:cloud-plugin-network-srx:jar:4.17.1.0-SNAPSHOT: Could not find artifact com.cloud.com.f5:icontrol:jar:1.0 in repo.jenkins-ci.org.releases (https://repo.jenkins-ci.org/releases/) -> [Help 1]

**Comment by nvazquez** [comment]
@ahmadamirahmadi007 after placing the files on the deps/ directory have you run the `install-non-sh.sh` script? This would install the missing dependency into your maven repository. Can you please retry building after running this script?

**Comment by ahmadamirahmadi007** [comment]
build was done with -Dnoredist parameter but i still have problems in Creating cluster stage with Error Unknown API command: addVmwareDc.
what can i do?

**Comment by nvazquez** [comment]
@ahmadamirahmadi007 you can add the `-Dnoredist` to your jetty run command

**Comment by shwstppr** [comment]
@ahmadamirahmadi007 this may help https://github.com/shapeblue/hackerbook/blob/main/2-dev.md#building-cloudstack

**Comment by ahmadamirahmadi007** [comment]
> @ahmadamirahmadi007 you can add the `-Dnoredist` to your jetty run command
 what's the diffrence between installing cloudstack via debian packages created from "mvn clean install -P systemvm,developer -Dnoredist" and mvn -pl :cloud-client-ui jetty:run. Both are the same result for me about Unknow API

**Comment by nvazquez** [comment]
Hi @ahmadamirahmadi007 the problem is that even though you built using noredist then you have not started the server with it. Please execute: `mvn -pl :cloud-client-ui jetty:run -Dnoredist`, this should include the Vmware packages after build using `mvn clean install -P systemvm,developer -Dnoredist`
