### ISSUE TITLE
Console not working with Primate UI

### ISSUE THREAD

**Issue by cdfgallo** [apache/cloudstack#8113]
##### ISSUE TYPE

 * Bug Report

##### COMPONENT NAME

~~~
UI
~~~

##### CLOUDSTACK VERSION

~~~
4.18.0.0
~~~

##### OS / ENVIRONMENT

CentOS 7

##### SUMMARY

Upgrading from Cloudstack version 4.17.2.0 to 4.18.0.0, if you use the primate interface and try to open the VNC console on any instance (no matter the privileges of the user account) it does not work and you obtain only "failed" message.

##### STEPS TO REPRODUCE

~~~
Upgrade from CS4.17.2.0 to 4.18.0.0 and use the Primate interface. The VNC console won't be accessible.
~~~

##### EXPECTED RESULTS

~~~
VNC console normally working as in version 4.17.2.0
~~~

##### ACTUAL RESULTS

~~~
Nothing happens and you receive "failed" message
~~~

**Comment by shwstppr** [comment]
@cdfgallo since 4.18.0 added API driven console, can you please check if you are getting any error in the management server logs?

cc @nvazquez

**Comment by DaanHoogland** [comment]
@cdfgallo I can confirm that in 4.18.0 there is a problem but this is solved in 4.18.1. If you upgrade and recreate the console proxy, it should work.

**Comment by cdfgallo** [comment]
> @cdfgallo since 4.18.0 added API driven console, can you please check if you are getting any error in the management server logs?
> 
> cc @nvazquez

unfortunately I can't find any log on the management server nor on the CPVM

**Comment by nvazquez** [comment]
Hi @cdfgallo can you increase the log level on the log4j.xml configuration file on the CPVM from INFO to DEBUG? After that, can you retry accessing consoles and check if something is logged on the cloud.log file on the CPVM?

**Comment by shwstppr** [comment]
@cdfgallo cc @nvazquez you may also check if `createConsoleEndpoint` API is executing fine

**Comment by DaanHoogland** [comment]
> @cdfgallo I can confirm that in 4.18.0 there is a problem but this is solved in 4.18.1. If you upgrade and recreate the console proxy, it should work.

@cdfgallo @shwstppr @nvazquez I have reproduced the error in 4.18.0 and seen it was gone after upgrading to 4.18.1. I didn't check what PR fixed it but closing this as it is fixed.

**Comment by cdfgallo** [comment]
Hello @DaanHoogland, I just upgrade my CS installation to version 4.18.1 but I can confirm you that I'm facing the same issue on this version too.
I tried re-create the CPVM (which is working with the new UI) but it still do not work

From the management node I found only this log


2023-10-29 09:34:22,378 DEBUG [c.c.u.AccountManagerImpl] (qtp1444635922-3124:null) (logid:) Access to VM instance {"id":298,"instanceName":"i-6-298-VM","type":"User","uuid":"bd0b24cf-0ede-45d0-a857-63e4e292f1dc"} granted to Account [{"accountName":"xxxx","id":141,"uuid":"f5b5cab6-025e-489c-9a4e-efde296bdcd3"}] by DomainChecker
2023-10-29 09:34:22,385 WARN  [c.c.s.ConsoleProxyServlet] (qtp1444635922-3124:null) (logid:) Null sid in URL.

**Comment by DaanHoogland** [comment]
ok @cdfgallo , so there is probably something extra going on. I'll reopen the issue.

**Comment by DaanHoogland** [comment]
@nvazquez @JoaoJandre , could you have a look as you are probably the most recent developers on the console proxy?

**Comment by JoaoJandre** [comment]
Hey @cdfgallo, 
In order to troubleshoot your problem we will need a little bit of context:
- Have you validated that you have access to the CPVM? Can you ping it from your machine?
- Could you follow @nvazquez instructions here https://github.com/apache/cloudstack/issues/8113#issuecomment-1770726550 and post the MGMT and CPVM logs from the process that you are trying to do?

**Comment by cdfgallo** [comment]
> Hey @cdfgallo, In order to troubleshoot your problem we will need a little bit of context:
> 
> * Have you validated that you have access to the CPVM? Can you ping it from your machine?
> * Could you follow @nvazquez instructions here [Console not working with Primate UI #8113 (comment)](https://github.com/apache/cloudstack/issues/8113#issuecomment-1770726550) and post the MGMT and CPVM logs from the process that you are trying to do?

Hello @JoaoJandre ,


yes, I have access to the CPVM, please note that this issue is present only from the primate UI.
I set the log level on DEBUG in the log4j-cloud.xml file, but unfortunatelly there are still no logs when I try to open the VNC console from the primate interface. From the MGMT server the only log I see is this one 
"
2023-10-29 09:34:22,378 DEBUG [c.c.u.AccountManagerImpl] (qtp1444635922-3124:null) (logid:) Access to VM instance {"id":298,"instanceName":"i-6-298-VM","type":"User","uuid":"bd0b24cf-0ede-45d0-a857-63e4e292f1dc"} granted to Account [{"accountName":"xxxx","id":141,"uuid":"f5b5cab6-025e-489c-9a4e-efde296bdcd3"}] by DomainChecker
2023-10-29 09:34:22,385 WARN [c.c.s.ConsoleProxyServlet] (qtp1444635922-3124:null) (logid:) Null sid in URL.
"

**Comment by JoaoJandre** [comment]
Hey @cdfgallo,
When you click on the button to open the console. The UI should call the API createConsoleEndpoint. And this API should log something on the management server. So that we are on the same page, can you please do the following test:

1. On your browser, open your browser console (F12 on Firefox and Chrome) and go to the network tab.
2. Click on the button to open the VM console. You should see a new entry on the network log that refers to the API call that the UI is making. Can you confirm that the API is being called? If so, could you share the contents of the API request?
3. If you confirm that the API is being called, you should get at least a few logs of the process. You could try using something like `grep -i 'createConsoleEndpoint' <mgmt-log-file>` to get the start of the process's logs. From here, you can grep using the logid of the process to get the rest of the logs.

If you make it to the end of step 3. Could you please share the logs that you captured?

**Comment by cdfgallo** [comment]
Hi @JoaoJandre ,

I've done the test you required and I can confirm you that, with the primate UI, the API createConsoleEndpoint is not being called.
Also from the management server I don't see any logs related to this.
Are there any other tests I can do for this issue?

**Comment by JoaoJandre** [comment]
Hello @cdfgallo,

I've tried to reproduce your problem on a lab running on version `4.18.1.0`, but I was unable to.
On my setup, the UI calls the API correctly and I can access the console. 

![logbrwoser](https://github.com/apache/cloudstack/assets/48719461/1de4648d-0b0d-42c9-82ee-242f3563d09e)
![consolevm](https://github.com/apache/cloudstack/assets/48719461/d7c429e9-da0e-4549-959c-31ea057a583a)

Can you repeat the test using an anonymous tab?

**Comment by cdfgallo** [comment]
Hello @JoaoJandre ,

unfortunately I can confirm you the error is the same using an anonymous tab.
Here you can find a screen when I open the console on primate UI.

![console](https://github.com/apache/cloudstack/assets/110984295/8fe74364-ec39-49b8-ab57-a3f430485ec3)

**Comment by cdfgallo** [comment]
Hi @JoaoJandre ,

I open the console accessing the VM and then clicking on "view console" button.
Yes, indeed I see that the URL is quite different, but it used to work with version 4.17.2

![image](https://github.com/apache/cloudstack/assets/110984295/26d1eff7-7198-4d3b-8bc5-8f2612711450)

**Comment by JoaoJandre** [comment]
> Hi @JoaoJandre ,
> 
> I open the console accessing the VM and then clicking on "view console" button. Yes, indeed I see that the URL is quite different, but it used to work with version 4.17.2
> 
> ![image](https://private-user-images.githubusercontent.com/110984295/286167317-26d1eff7-7198-4d3b-8bc5-8f2612711450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDExOTI4MTAsIm5iZiI6MTcwMTE5MjUxMCwicGF0aCI6Ii8xMTA5ODQyOTUvMjg2MTY3MzE3LTI2ZDFlZmY3LTcxOTgtNGQzYi04YmM1LThmMjYxMjcxMTQ1MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOFQxNzI4MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mOGNlYzQ1MzA2MGYwYjk1NDBhZjQ1OTQ3NzRkOWU4NWEzYjAwZmFiYTNmOTdjNTI5MjA0MjIxMDFkNTY2ZGY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Qbt0IWRTQ78Ct7DehsAcAIYK4th7IthFJenxiLKI07g)

Hello @cdfgallo,
I can see from your screenshot that you're not using the GUI that is embedded with the community version. Otherwise, your UI should look something like this:
![2023-11-28_15-44](https://github.com/apache/cloudstack/assets/48719461/0fd427da-a7b0-4b62-875a-97fb63986de8)


PR #6577 changed the way consoles are managed in ACS; therefore, unfortunately I'll not be able to help you with a custom deployment. You might try contacting your vendor to get further help, if it is the case.

**Comment by nvazquez** [comment]
Hi @cdfgallo, as @JoaoJandre points out the UI seems to be missing the changes regarding the CloudStack UI about the latest console access enhancements.

As a workaround, you can use the createConsoleEndpoint API to generate an access URL and paste it in your browser.

Example:
````
(localcloud) 🐱 > create consoleendpoint virtualmachineid=27b3a356-cc0d-451f-8c20-0aca0b60487a 
{
  "consoleendpoint": {
    "success": true,
    "url": "http://xx.xx.xx.xx/resource/noVNC/vnc.html?autoconnect=true&port=8080&token=<TOKEN>",
    "websocket": {
      "host": "<HOST_IP>",
      "path": "websockify",
      "port": "8080",
      "token": "<TOKEN>"
    }
  }
}
````

Then copy the url field from the response in your browser to access the console. Can you try this approach?

**Comment by cdfgallo** [comment]
Hi @weizhouapache, I'm sorry for the late reply.
We are not using cloudstack-ui package.
We found a workaround for this so we can close this issue as I see it's related to a old customization.
thank you all for the support.
